on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: Build Site

permissions:
  contents: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build HTML site 🔧
        run: quarto render --to html

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _book
